### PR TITLE
Quick fix for minor bugs found when running benchmark

### PR DESCRIPTION
**Pull request by juimdpp**
* `subprocess.call` requires list of arguments instead of a string.
* Comparison of two strings requires the usage of `strcmp`.

### CODE REVIEW

**Review by widiba03304 — COMMENTED** [review]
Great! However, Strcmp is considered to be insecure, so it would be great if we change 'const char*' into 'std::string' or use 'strncmp'.

**Comment by widiba03304** [comment]
I just changed all occurrences of the `const char*` into `std::string` in C++ and found another `strcmp` in C API which should be `strncmp`.

**Comment by dostos** [comment]
@widiba03304 @juimdpp 
This broke all string formats that rely on the c-styled string (`%s` for printf) and requires a global change with an additional `.c_str()`.
I think forcing std::string types to const expressions (such as `ToString` utility function) is overkill. Why not just use `strncmp` or wrap const char* with std::string when we need a comparison?

**Comment by widiba03304** [comment]
@dostos My thought was to maintain all the methods and functions containing `ToString` to return `std::string` as some classes have `ToString` which returns `std::string`, for example, `SubgraphKey`. How about we keep the methods in class returning `std::string` and functions returning `const char*`?

**Comment by dostos** [comment]
Sounds good to me!

**Pull request merged**
